export const IMAGES = { 
    background: require("./background.png"),
    flag: require("/Users/clintononuoha/groceries-app/assets/images/flag.png"),
    onboarding: require("/Users/clintononuoha/groceries-app/assets/images/onboarding.png"),
    carrotlogo: require ("/Users/clintononuoha/groceries-app/assets/images/carrot-logo.png"),
    clogo: require ("/Users/clintononuoha/groceries-app/assets/images/carrotlogo.png"),
    groceries: require ("/Users/clintononuoha/groceries-app/assets/images/groceries.png"),
    logo: require ("/Users/clintononuoha/groceries-app/assets/images/logo.png"),
    googleIcon: require ("/Users/clintononuoha/groceries-app/assets/images/google-icon.png"),
    facebookIcon: require ("/Users/clintononuoha/groceries-app/assets/images/facebook-icon.png"),
    location: require ("/Users/clintononuoha/groceries-app/assets/images/location.png"),
    banana: require ("/Users/clintononuoha/groceries-app/assets/images/banana.png"),
    apple: require ("/Users/clintononuoha/groceries-app/assets/images/apple.png"),
    redpepper: require ("/Users/clintononuoha/groceries-app/assets/images/redpepper.png"),
    ginger: require ("/Users/clintononuoha/groceries-app/assets/images/ginger.png"),
    beef: require ("/Users/clintononuoha/groceries-app/assets/images/beef.png"),
    chicken: require ("/Users/clintononuoha/groceries-app/assets/images/chicken.png"),
    banner: require ("/Users/clintononuoha/groceries-app/assets/images/banner.png"),
    pulses: require ("/Users/clintononuoha/groceries-app/assets/images/pulse.png"),
    rice: require ("/Users/clintononuoha/groceries-app/assets/images/rice.png"),
    fruits: require ("/Users/clintononuoha/groceries-app/assets/images/fruits.png"),
    meat: require ("/Users/clintononuoha/groceries-app/assets/images/meat.png"),
    beverages: require ("/Users/clintononuoha/groceries-app/assets/images/beverage.png"),
    dairy: require ("/Users/clintononuoha/groceries-app/assets/images/milk.png"),
    bakery: require ("/Users/clintononuoha/groceries-app/assets/images/pastries.png"),
    oil: require ("/Users/clintononuoha/groceries-app/assets/images/oil.png"),
    dietcoke: require ("/Users/clintononuoha/groceries-app/assets/images/dietcoke.png"),
    sprite: require ("/Users/clintononuoha/groceries-app/assets/images/sprite.png"),
    applegrape: require ("/Users/clintononuoha/groceries-app/assets/images/applegrape.png"),
    orangejuice: require ("/Users/clintononuoha/groceries-app/assets/images/orangejuice.png"),
    cocacola: require ("/Users/clintononuoha/groceries-app/assets/images/cocacola.png"),
    pepsi: require ("/Users/clintononuoha/groceries-app/assets/images/pepsi.png"),
    addButton: require ("/Users/clintononuoha/groceries-app/assets/images/addbutton.png"),
    share: require ("/Users/clintononuoha/groceries-app/assets/images/share.png"),
    filter: require ("/Users/clintononuoha/groceries-app/assets/images/filter.png"),
    shopActive: require ("/Users/clintononuoha/groceries-app/assets/images/shopActive.png"),
    shopInactive: require ("/Users/clintononuoha/groceries-app/assets/images/shopInactive.png"),
    exploreActive: require ("/Users/clintononuoha/groceries-app/assets/images/exploreActive.png"),
    exploreInactive: require ("/Users/clintononuoha/groceries-app/assets/images/exploreInactive.png"),
    cartActive: require ("/Users/clintononuoha/groceries-app/assets/images/cartActive.png"),
    cartInactive: require ("/Users/clintononuoha/groceries-app/assets/images/cartInactive.png"),
    favoriteActive: require ("/Users/clintononuoha/groceries-app/assets/images/favoriteActive.png"),
    favoriteInactive: require ("assets/images/favoriteInactive.png"),
    accountActive: require ("assets/images/profileActive.png"),
    accountInactive: require ("assets/images/profileInactive.png"),
    egg: require ("assets/images/egg.png"),
    backg: require("./backg.png"),
    orders: require ("assets/images/ordersicon.png"),
    detailsicon: require ("assets/images/detailsicon.png"),
    deliveryicon: require("assets/images/deliveryicon.png"),
    payment: require ("assets/images/Vector icon.png"),
    promo: require ("assets/images/Promo Cord icon.png"),
    bell: require ("assets/images/Bell icon.png"),
    helpicon: require("assets/images/help icon.png"),
    about: require("assets/images/about icon.png"),
    logout: require("assets/images/logout.png"),
    forward: require ("assets/images/back arrow.png"),
    cardImage: require("assets/images/card.png"),
    orderAccepted: require ("assets/images/orderaccepted.png"),
};