export const IMAGES = { 
    background: require("./background.png"),
    flag: require("/Users/clintononuoha/groceries-app/assets/images/flag.png"),
    onboarding: require("/Users/clintononuoha/groceries-app/assets/images/onboarding.png"),
    carrotlogo: require ("/Users/clintononuoha/groceries-app/assets/images/carrot-logo.png"),
    clogo: require ("/Users/clintononuoha/groceries-app/assets/images/carrotlogo.png"),
    groceries: require ("/Users/clintononuoha/groceries-app/assets/images/groceries.png"),
    logo: require ("/Users/clintononuoha/groceries-app/assets/images/logo.png"),
    googleIcon: require ("/Users/clintononuoha/groceries-app/assets/images/google-icon.png"),
    facebookIcon: require ("/Users/clintononuoha/groceries-app/assets/images/facebook-icon.png"),
    location: require ("/Users/clintononuoha/groceries-app/assets/images/location.png"),
    banana: require ("/Users/clintononuoha/groceries-app/assets/images/banana.png"),
    apple: require ("/Users/clintononuoha/groceries-app/assets/images/apple.png"),
    redpepper: require ("/Users/clintononuoha/groceries-app/assets/images/redpepper.png"),
    ginger: require ("/Users/clintononuoha/groceries-app/assets/images/ginger.png"),
    beef: require ("/Users/clintononuoha/groceries-app/assets/images/beef.png"),
    chicken: require ("/Users/clintononuoha/groceries-app/assets/images/chicken.png"),
    banner: require ("/Users/clintononuoha/groceries-app/assets/images/banner.png"),
    pulses: require ("/Users/clintononuoha/groceries-app/assets/images/pulse.png"),
    rice: require ("/Users/clintononuoha/groceries-app/assets/images/rice.png"),
    fruits: require ("/Users/clintononuoha/groceries-app/assets/images/fruits.png"),
    meat: require ("/Users/clintononuoha/groceries-app/assets/images/meat.png"),
    beverages: require ("/Users/clintononuoha/groceries-app/assets/images/beverage.png"),
    dairy: require ("/Users/clintononuoha/groceries-app/assets/images/milk.png"),
    bakery: require ("/Users/clintononuoha/groceries-app/assets/images/pastries.png"),
    oil: require ("/Users/clintononuoha/groceries-app/assets/images/oil.png"),
    dietcoke: require ("/Users/clintononuoha/groceries-app/assets/images/dietcoke.png"),
    sprite: require ("/Users/clintononuoha/groceries-app/assets/images/sprite.png"),
    applegrape: require ("/Users/clintononuoha/groceries-app/assets/images/applegrape.png"),
    orangejuice: require ("/Users/clintononuoha/groceries-app/assets/images/orangejuice.png"),
    cocacola: require ("/Users/clintononuoha/groceries-app/assets/images/cocacola.png"),
    pepsi: require ("/Users/clintononuoha/groceries-app/assets/images/pepsi.png"),
    addButton: require ("/Users/clintononuoha/groceries-app/assets/images/addbutton.png"),
};