export const IMAGES = { 
    background: require("../images/background.png"),
    flag: require("../images/flag.png"),
    onboarding: require("../images/onboarding.png"),
    carrotlogo: require ("../images/carrot-logo.png"),
    clogo: require ("../images/carrotlogo.png"),
    groceries: require ("../images/groceries.png"),
    logo: require ("../images/logo.png"),
    googleIcon: require ("../images/google-icon.png"),
    facebookIcon: require ("../images/facebook-icon.png"),
    location: require ("../images/location.png"),
    banana: require ("../images/banana.png"),
    apple: require ("../images/apple.png"),
    redpepper: require ("../images/redpepper.png"),
    ginger: require ("../images/ginger.png"),
    beef: require ("../images/beef.png"),
    chicken: require ("../images/chicken.png"),
    banner: require ("../images/banner.png"),
    pulses: require ("../images/pulse.png"),
    rice: require ("../images/rice.png"),
    fruits: require ("../images/fruits.png"),
    meat: require ("../images/meat.png"),
    beverages: require ("../images/beverage.png"),
    dairy: require ("../images/milk.png"),
    bakery: require ("../images/pastries.png"),
    oil: require ("../images/oil.png"),
    dietcoke: require ("../images/dietcoke.png"),
    sprite: require ("../images/sprite.png"),
    applegrape: require ("../images/applegrape.png"),
    orangejuice: require ("../images/orangejuice.png"),
    cocacola: require ("../images/cocacola.png"),
    pepsi: require ("../images/pepsi.png"),
    addButton: require ("../images/addbutton.png"),
    share: require ("../images/share.png"),
    filter: require ("../images/filter.png"),
    shopActive: require ("../images/shopActive.png"),
    shopInactive: require ("../images/shopInactive.png"),
    exploreActive: require ("../images/exploreActive.png"),
    exploreInactive: require ("../images/exploreInactive.png"),
    cartActive: require ("../images/cartActive.png"),
    cartInactive: require ("../images/cartInactive.png"),
    favoriteActive: require ("../images/favoriteActive.png"),
    favoriteInactive: require ("assets/images/favoriteInactive.png"),
    accountActive: require ("assets/images/profileActive.png"),
    accountInactive: require ("assets/images/profileInactive.png"),
    egg: require ("../images/egg.png"),
    backg: require("../images/backg.png"),
    orders: require ("../images/ordersicon.png"),
    detailsicon: require ("../images/detailsicon.png"),
    deliveryicon: require("../images/deliveryicon.png"),
    payment: require ("../images/Vector icon.png"),
    promo: require ("../images/Promo Cord icon.png"),
    bell: require ("../images/Bell icon.png"),
    helpicon: require("../images/help icon.png"),
    about: require("../images/about icon.png"),
    logout: require("../images/logout.png"),
    forward: require ("../images/back arrow.png"),
    cardImage: require("../images/card.png"),
    orderAccepted: require ("../images/orderaccepted.png"),
};